# Generated by Django 3.0.5 on 2020-05-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventKey', models.TextField()),
                ('date', models.DateTimeField()),
                ('actor', models.TextField()),
                ('payload', models.TextField()),
                ('received_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
