# Generated by Django 3.0.5 on 2020-05-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbucket_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
