# Generated by Django 3.0.5 on 2020-05-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitbucket_agent', '0002_report_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='token',
            new_name='signature',
        ),
    ]
