# Generated by Django 3.0.5 on 2020-05-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitbucket_agent', '0003_auto_20200515_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='signature',
            new_name='HMAC',
        ),
    ]
