# Generated by Django 3.0.5 on 2020-05-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitbucket_agent', '0004_auto_20200515_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='payload',
            new_name='raw',
        ),
    ]
